services:
  # API Server
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    container_name: thematic-excel-lens-api
    ports:
      - "${API_PORT:-3001}:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    depends_on: []
    restart: unless-stopped
    networks:
      - thematic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Applicazione principale
  thematic-excel-lens:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: thematic-excel-lens-app
    ports:
      - "${APP_PORT:-3007}:80"
    env_file:
      - .env
    environment:
      # Variabili d'ambiente per l'applicazione
      - NODE_ENV=${NODE_ENV:-production}
      - VITE_API_URL=http://api-server:3001
      - VITE_APP_NAME=${VITE_APP_NAME:-AnaTema}
      
      # Configurazione file e funzionalità
      - VITE_MAX_FILE_SIZE=${VITE_MAX_FILE_SIZE:-50MB}
      - VITE_ALLOWED_FILE_TYPES=${VITE_ALLOWED_FILE_TYPES:-xlsx,xls,csv}
      - VITE_ENABLE_ANALYTICS=${VITE_ENABLE_ANALYTICS:-true}
      - VITE_AUTO_SAVE_INTERVAL=${VITE_AUTO_SAVE_INTERVAL:-30000}
    volumes:
      # Volume persistente per i dati dell'applicazione
      - app_data:/app/data
      # Volume per i file temporanei e cache
      - temp_data:/tmp/app
      # Volume per i log (opzionale)
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - thematic_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database Redis per cache e sessioni (opzionale)
  redis:
    image: redis:7-alpine
    container_name: thematic-excel-lens-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      # Volume persistente per Redis
      - redis_data:/data
    restart: unless-stopped
    networks:
      - thematic_network
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}

  # Database PostgreSQL per dati persistenti
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: thematic-excel-lens-postgres
  #   ports:
  #     - "${POSTGRES_PORT:-5432}:5432"
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER:-postgres}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - POSTGRES_DB=${POSTGRES_DB:-thematic_lens}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./docker/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
  #   restart: unless-stopped
  #   networks:
  #     - thematic_network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

  # Servizio di backup automatico (opzionale)
  backup:
    image: alpine:latest
    container_name: thematic-excel-lens-backup
    environment:
      - BACKUP_INTERVAL=${BACKUP_INTERVAL:-86400} # 24 ore in secondi
      - BACKUP_RETENTION=${BACKUP_RETENTION:-7} # mantieni 7 backup
    volumes:
      - app_data:/source:ro
      - ./backups:/backups
    restart: unless-stopped
    networks:
      - thematic_network
    command: >
      sh -c "
        while true; do
          echo 'Creazione backup...'
          tar -czf /backups/backup_$(date +%Y%m%d_%H%M%S).tar.gz -C /source .
          echo 'Backup completato'
          
          echo 'Pulizia backup vecchi...'
          ls -t /backups/backup_*.tar.gz | tail -n +$$((${BACKUP_RETENTION} + 1)) | xargs -r rm
          
          echo 'Prossimo backup tra ${BACKUP_INTERVAL} secondi'
          sleep ${BACKUP_INTERVAL}
        done
      "

# Volumi persistenti
volumes:
  # Volume principale per i dati dell'applicazione
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}
  
  # Volume per i dati Redis
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${REDIS_DATA_PATH:-./redis-data}

  # Volume per i dati PostgreSQL
  # postgres_data:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${POSTGRES_DATA_PATH:-./postgres-data}
  
  # Volume per file temporanei
  temp_data:
    driver: local

# Rete personalizzata
networks:
  thematic_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
